const Product = require("../models/Product")

const productData = [
    {
        name: 'Logitech Wireless Combo MK270',
        description: 'The design of this keyboard creates a comfortable typing experience thanks to the low-profile, quiet keys and standard layout with full-size F-keys, number pad, and arrow keys',
        price: 29.99,
        SKU: 123,
        origin: 'Brampton',
        category_id: 1,
        user_id: 1,
        shipping_id: 1,
        stock: 10,
        length: 441,
        width: 139,
        height: 18,
        dimension_units: "mm",
        weight: 498,
        weight_units: "g",
    },
    {
        name: 'Axios',
        description: 'Axios is a simple promise based HTTP client for the browser and node. js. Axios provides a simple to use library in a small package with a very extensible interface. Get Started View on GitHub.',
        price: 9.99,
        SKU: 321,
        origin: 'Toronto',
        category_id: 2,
        user_id: 2,
        shipping_id: 2
    },
    {
        name: 'Django',
        description: 'Django REST framework is a powerful and flexible toolkit for building Web APIs.',
        price: 19.99,
        SKU: 213,
        origin: 'Vancouver',
        category_id: 2,
        user_id: 3,
        shipping_id: 3
    },
    {
        name: 'LG 31.5" 4K UHD Monitor',
        description: 'This 32" LED beast offers stunning 4K Ultra HD resolution with optimal colour accuracy and effortless image reproduction.',
        price: 379.99,
        SKU: 100,
        origin: 'Los Angeles',
        category_id: 1,
        user_id: 4,
        shipping_id: 2,
        stock: 20,
        length: 700,
        width: 500,
        height: 200,
        dimension_units: "mm",
        weight: 7000,
        weight_units: "g",
    },
    {
        name: 'Express',
        description: 'Express.js, or simply Express, is a back end web application framework for Node.js, released as free and open-source software under the MIT License.',
        price: 0.00,
        SKU: 101,
        origin: 'New York',
        category_id: 2,
        user_id: 5,
        shipping_id: 2
    },
    {
        name: 'Boostrap',
        description: 'Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. ',
        price: 0.00,
        SKU: 102,
        origin: 'Silicon Valley',
        category_id: 2,
        user_id: 6,
        shipping_id: 3
    },
    {
        name: 'Apple MacBook Air 13.3"',
        description: 'Apples thinnest and lightest notebook gets supercharged with the Apple M1 chip.',
        price: 1299.99,
        SKU: 103,
        origin: 'Los Angeles',
        category_id: 1,
        user_id: 7,
        shipping_id: 1,
        stock: 3,
        length: 300,
        width: 210,
        height: 50,
        dimension_units: "mm",
        weight: 5000,
        weight_units: "g",
    },
    {
        name: 'Acer Aspire XC Desktop PC',
        description: 'Experience reliable speed and performance for all your daily computing tasks with this Acer Aspire XC desktop PC.',
        price: 469.99,
        SKU: 104,
        origin: 'San Francisco',
        category_id: 1,
        user_id: 8,
        shipping_id: 3,
        stock: 5,
        length: 100,
        width: 290,
        height: 330,
        dimension_units: "mm",
        weight: 20000,
        weight_units: "g",
    },
    {
        name: 'Seagate Basic 2TB USB 3.0 External Travel Drive',
        description: 'Its 2TB of storage space can accommodate large applications, games, software, and media files.',
        price: 69.99,
        SKU: 105,
        origin: 'Toronto',
        category_id: 1,
        user_id: 9,
        shipping_id: 2,
        stock: 15,
        length: 80,
        width: 117,
        height: 14,
        dimension_units: "mm",
        weight: 375,
        weight_units: "g",
    },
    {
        name: 'Corsair Ironclaw RGB 18000 DPI Optical Gaming Mouse',
        description: 'The Corsair Ironclaw optical gaming mouse sets a benchmark when it comes to performance and accuracy.',
        price: 79.99,
        SKU: 106,
        origin: 'Mississauga',
        category_id: 1,
        user_id: 10,
        shipping_id: 3,
        stock: 25,
        length: 17,
        width: 8,
        height: 11,
        dimension_units: "mm",
        weight: 1,
        weight_units: "g",
    },
    {
        name: 'Manhattan Wired Computer Keyboard',
        description: 'Basic Keyboard - with 5ft USB-A Cable, 104-keys, Foldable Stands - Compatible for Windows, PC, Laptop',
        price: 11.99,
        SKU: 107,
        origin: 'Toronto',
        category_id: 1,
        user_id: 1,
        shipping_id: 1,
        stock: 8,
        length: 450,
        width: 150,
        height: 35,
        dimension_units: "mm",
        weight: 425,
        weight_units: "g",
    },
    {
        name: 'Acer SB220Q bi 21.5 Inches Full HD',
        description: '21.5 inches Full HD (1920 x 1080) widescreen IPS display',
        price: 129.99,
        SKU: 108,
        origin: 'Toronto',
        category_id: 1,
        user_id: 2,
        shipping_id: 3,
        stock: 5,
        length: 200,
        width: 500,
        height: 350,
        dimension_units: "mm",
        weight: 2721,
        weight_units: "g",
    },
    {
        name: 'ASUS VivoBook 15 K513 Thin & Light Laptop, 15.6” FHD Display',
        description: 'Latest 11th generation Intel Core i7-1165G7 Quad Core Processor (12M Cache, up to 4.70 GHz) and discrete NVIDIA GeForce MX350 graphics',
        price: 949.99,
        SKU: 109,
        origin: 'Los Angeles',
        category_id: 1,
        user_id: 3,
        shipping_id: 2,
        stock: 2,
        length: 355,
        width: 250,
        height: 25,
        dimension_units: "mm",
        weight: 1800,
        weight_units: "g",
    },
    {
        name: 'LED Wireless Mouse, Uiosmuph G12 Slim',
        description: 'Rechargeable Wireless Silent Mouse, 2.4G Portable USB Optical Wireless Computer Mice with USB Receiver and Type C Adapter',
        price: 12.99,
        SKU: 110,
        origin: 'Vancouver',
        category_id: 1,
        user_id: 4,
        shipping_id: 1,
        stock: 15,
        length: 127,
        width: 75,
        height: 25,
        dimension_units: "mm",
        weight: 50,
        weight_units: "g",
    },
    {
        name: 'React',
        description: 'React is a free and open-source front-end JavaScript library for building user interfaces based on UI components.',
        price: 0.00,
        SKU: 111,
        origin: 'Silicon Valley',
        category_id: 2,
        user_id: 5,
        shipping_id: 3
    },

];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;